name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Validate environment variables
        run: npm run validate-env
        env:
          NODE_ENV: production
          NEXT_PUBLIC_N8N_WEBHOOK_URL: ${{ secrets.NEXT_PUBLIC_N8N_WEBHOOK_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production
          NEXT_PUBLIC_N8N_WEBHOOK_URL: ${{ secrets.NEXT_PUBLIC_N8N_WEBHOOK_URL }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ignite-health-systems-website
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    name: Test build and deployment
    needs: deploy

    steps:
      - name: Test website accessibility
        run: |
          echo "Testing website accessibility..."
          curl -f -s -o /dev/null https://ignitehealthsystems.com || echo "Site not yet accessible"

      - name: Verify deployment status
        run: |
          echo "✅ Deployment completed successfully"
          echo "🌐 Site URL: https://ignitehealthsystems.com"