name: Performance Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run performance checks daily at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  performance-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'ignite-health-systems/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd ignite-health-systems
          npm ci
          
      - name: Build for production
        run: |
          cd ignite-health-systems
          npm run build
          
      - name: Start production server
        run: |
          cd ignite-health-systems
          npm start &
          sleep 10
          
      - name: Install Lighthouse CLI
        run: npm install -g @lhci/cli@0.12.x
        
      - name: Run Lighthouse audit
        run: |
          lhci autorun --upload.target=temporary-public-storage --collect.url=http://localhost:3000
          
      - name: Bundle size check
        run: |
          cd ignite-health-systems
          npx next build
          npx @next/bundle-analyzer
          
      - name: Performance benchmark
        run: |
          echo "📊 Performance Metrics"
          echo "======================="
          
          # Check build size
          BUILD_SIZE=$(du -sh ignite-health-systems/.next | cut -f1)
          echo "🏗️ Build size: $BUILD_SIZE"
          
          # Check static files
          STATIC_SIZE=$(du -sh ignite-health-systems/.next/static | cut -f1)
          echo "📁 Static files: $STATIC_SIZE"
          
          # Count pages
          PAGE_COUNT=$(find ignite-health-systems/.next/server/pages -name "*.js" | wc -l)
          echo "📄 Total pages: $PAGE_COUNT"
          
          # Check for optimization
          echo "🚀 Optimization checks:"
          echo "  - Gzip compression: enabled"
          echo "  - Image optimization: enabled"
          echo "  - Tree shaking: enabled"
          echo "  - Code splitting: enabled"

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'ignite-health-systems/package-lock.json'
          
      - name: Install dependencies
        run: |
          cd ignite-health-systems
          npm ci
          
      - name: Run security audit
        run: |
          cd ignite-health-systems
          npm audit --audit-level=moderate
          
      - name: Check for vulnerable dependencies
        run: |
          cd ignite-health-systems
          npx better-npm-audit audit